---
apiVersion: v1
kind: Service
metadata:
  name: exoplanet-prod-fastapi-nodeport-service
spec:
  type: NodePort
  selector:
    app: exoplanet-prod-fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000